package org.giddap.dreamfactory.leetcode.onlinejudge;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import org.giddap.dreamfactory.leetcode.onlinejudge.implementations.Q017LetterCombinationsOfPhoneNumberImpl;
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.assertEquals;

public class Q017LetterCombinationsOfPhoneNumberTest {
    private Q017LetterCombinationsOfPhoneNumber solution = new Q017LetterCombinationsOfPhoneNumberImpl();

    @Test
    public void small01() {
        ArrayList<String> actual = solution.letterCombinations("23");
        ArrayList<String> expected = Lists.newArrayList("ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf");

        assertEquals(expected.size(), actual.size());
        assertEquals(Sets.newHashSet(expected), Sets.newHashSet(actual));
    }
}

/*
Test cases
Input	 Output	 Expected
""	[""]	[""]
"2"	["a","b","c"]	["a","b","c"]
"3"	["d","e","f"]	["d","e","f"]
"4"	["g","h","i"]	["g","h","i"]
"5"	["j","k","l"]	["j","k","l"]
"6"	["m","n","o"]	["m","n","o"]
"7"	["p","q","r","s"]	["p","q","r","s"]
"8"	["t","u","v"]	["t","u","v"]
"9"	["w","x","y","z"]	["w","x","y","z"]
"22"	["aa","ba","ca","ab","bb","cb","ac","bc","cc"]	["aa","ba","ca","ab","bb","cb","ac","bc","cc"]
"23"	["ad","bd","cd","ae","be","ce","af","bf","cf"]	["ad","bd","cd","ae","be","ce","af","bf","cf"]
"234"	["adg","bdg","cdg","aeg","beg","ceg","afg","bfg","cfg","adh","bdh","cdh","aeh","beh","ceh","afh","bfh","cfh","adi","bdi","cdi","aei","bei","cei","afi","bfi","cfi"]	["adg","bdg","cdg","aeg","beg","ceg","afg","bfg","cfg","adh","bdh","cdh","aeh","beh","ceh","afh","bfh","cfh","adi","bdi","cdi","aei","bei","cei","afi","bfi","cfi"]
"32"	["da","ea","fa","db","eb","fb","dc","ec","fc"]	["da","ea","fa","db","eb","fb","dc","ec","fc"]
"243"	["agd","bgd","cgd","ahd","bhd","chd","aid","bid","cid","age","bge","cge","ahe","bhe","che","aie","bie","cie","agf","bgf","cgf","ahf","bhf","chf","aif","bif","cif"]	["agd","bgd","cgd","ahd","bhd","chd","aid","bid","cid","age","bge","cge","ahe","bhe","che","aie","bie","cie","agf","bgf","cgf","ahf","bhf","chf","aif","bif","cif"]
"432"	["gda","hda","ida","gea","hea","iea","gfa","hfa","ifa","gdb","hdb","idb","geb","heb","ieb","gfb","hfb","ifb","gdc","hdc","idc","gec","hec","iec","gfc","hfc","ifc"]	["gda","hda","ida","gea","hea","iea","gfa","hfa","ifa","gdb","hdb","idb","geb","heb","ieb","gfb","hfb","ifb","gdc","hdc","idc","gec","hec","iec","gfc","hfc","ifc"]
"342"	["dga","ega","fga","dha","eha","fha","dia","eia","fia","dgb","egb","fgb","dhb","ehb","fhb","dib","eib","fib","dgc","egc","fgc","dhc","ehc","fhc","dic","eic","fic"]	["dga","ega","fga","dha","eha","fha","dia","eia","fia","dgb","egb","fgb","dhb","ehb","fhb","dib","eib","fib","dgc","egc","fgc","dhc","ehc","fhc","dic","eic","fic"]
"324"	["dag","eag","fag","dbg","ebg","fbg","dcg","ecg","fcg","dah","eah","fah","dbh","ebh","fbh","dch","ech","fch","dai","eai","fai","dbi","ebi","fbi","dci","eci","fci"]	["dag","eag","fag","dbg","ebg","fbg","dcg","ecg","fcg","dah","eah","fah","dbh","ebh","fbh","dch","ech","fch","dai","eai","fai","dbi","ebi","fbi","dci","eci","fci"]
"423"	["gad","had","iad","gbd","hbd","ibd","gcd","hcd","icd","gae","hae","iae","gbe","hbe","ibe","gce","hce","ice","gaf","haf","iaf","gbf","hbf","ibf","gcf","hcf","icf"]	["gad","had","iad","gbd","hbd","ibd","gcd","hcd","icd","gae","hae","iae","gbe","hbe","ibe","gce","hce","ice","gaf","haf","iaf","gbf","hbf","ibf","gcf","hcf","icf"]
"999"	["www","xww","yww","zww","wxw","xxw","yxw","zxw","wyw","xyw","yyw","zyw","wzw","xzw","yzw","zzw","wwx","xwx","ywx","zwx","wxx","xxx","yxx","zxx","wyx","xyx","yyx","zyx","wzx","xzx","yzx","zzx","wwy","xwy","ywy","zwy","wxy","xxy","yxy","zxy","wyy","xyy","yyy","zyy","wzy","xzy","yzy","zzy","wwz","xwz","ywz","zwz","wxz","xxz","yxz","zxz","wyz","xyz","yyz","zyz","wzz","xzz","yzz","zzz"]	["www","xww","yww","zww","wxw","xxw","yxw","zxw","wyw","xyw","yyw","zyw","wzw","xzw","yzw","zzw","wwx","xwx","ywx","zwx","wxx","xxx","yxx","zxx","wyx","xyx","yyx","zyx","wzx","xzx","yzx","zzx","wwy","xwy","ywy","zwy","wxy","xxy","yxy","zxy","wyy","xyy","yyy","zyy","wzy","xzy","yzy","zzy","wwz","xwz","ywz","zwz","wxz","xxz","yxz","zxz","wyz","xyz","yyz","zyz","wzz","xzz","yzz","zzz"]
"455"	["gjj","hjj","ijj","gkj","hkj","ikj","glj","hlj","ilj","gjk","hjk","ijk","gkk","hkk","ikk","glk","hlk","ilk","gjl","hjl","ijl","gkl","hkl","ikl","gll","hll","ill"]	["gjj","hjj","ijj","gkj","hkj","ikj","glj","hlj","ilj","gjk","hjk","ijk","gkk","hkk","ikk","glk","hlk","ilk","gjl","hjl","ijl","gkl","hkl","ikl","gll","hll","ill"]
"338"	["ddt","edt","fdt","det","eet","fet","dft","eft","fft","ddu","edu","fdu","deu","eeu","feu","dfu","efu","ffu","ddv","edv","fdv","dev","eev","fev","dfv","efv","ffv"]	["ddt","edt","fdt","det","eet","fet","dft","eft","fft","ddu","edu","fdu","deu","eeu","feu","dfu","efu","ffu","ddv","edv","fdv","dev","eev","fev","dfv","efv","ffv"]
"5678"	["jmpt","kmpt","lmpt","jnpt","knpt","lnpt","jopt","kopt","lopt","jmqt","kmqt","lmqt","jnqt","knqt","lnqt","joqt","koqt","loqt","jmrt","kmrt","lmrt","jnrt","knrt","lnrt","jort","kort","lort","jmst","kmst","lmst","jnst","knst","lnst","jost","kost","lost","jmpu","kmpu","lmpu","jnpu","knpu","lnpu","jopu","kopu","lopu","jmqu","kmqu","lmqu","jnqu","knqu","lnqu","joqu","koqu","loqu","jmru","kmru","lmru","jnru","knru","lnru","joru","koru","loru","jmsu","kmsu","lmsu","jnsu","knsu","lnsu","josu","kosu","losu","jmpv","kmpv","lmpv","jnpv","knpv","lnpv","jopv","kopv","lopv","jmqv","kmqv","lmqv","jnqv","knqv","lnqv","joqv","koqv","loqv","jmrv","kmrv","lmrv","jnrv","knrv","lnrv","jorv","korv","lorv","jmsv","kmsv","lmsv","jnsv","knsv","lnsv","josv","kosv","losv"]	["jmpt","kmpt","lmpt","jnpt","knpt","lnpt","jopt","kopt","lopt","jmqt","kmqt","lmqt","jnqt","knqt","lnqt","joqt","koqt","loqt","jmrt","kmrt","lmrt","jnrt","knrt","lnrt","jort","kort","lort","jmst","kmst","lmst","jnst","knst","lnst","jost","kost","lost","jmpu","kmpu","lmpu","jnpu","knpu","lnpu","jopu","kopu","lopu","jmqu","kmqu","lmqu","jnqu","knqu","lnqu","joqu","koqu","loqu","jmru","kmru","lmru","jnru","knru","lnru","joru","koru","loru","jmsu","kmsu","lmsu","jnsu","knsu","lnsu","josu","kosu","losu","jmpv","kmpv","lmpv","jnpv","knpv","lnpv","jopv","kopv","lopv","jmqv","kmqv","lmqv","jnqv","knqv","lnqv","joqv","koqv","loqv","jmrv","kmrv","lmrv","jnrv","knrv","lnrv","jorv","korv","lorv","jmsv","kmsv","lmsv","jnsv","knsv","lnsv","josv","kosv","losv"]
"9387"	["wdtp","xdtp","ydtp","zdtp","wetp","xetp","yetp","zetp","wftp","xftp","yftp","zftp","wdup","xdup","ydup","zdup","weup","xeup","yeup","zeup","wfup","xfup","yfup","zfup","wdvp","xdvp","ydvp","zdvp","wevp","xevp","yevp","zevp","wfvp","xfvp","yfvp","zfvp","wdtq","xdtq","ydtq","zdtq","wetq","xetq","yetq","zetq","wftq","xftq","yftq","zftq","wduq","xduq","yduq","zduq","weuq","xeuq","yeuq","zeuq","wfuq","xfuq","yfuq","zfuq","wdvq","xdvq","ydvq","zdvq","wevq","xevq","yevq","zevq","wfvq","xfvq","yfvq","zfvq","wdtr","xdtr","ydtr","zdtr","wetr","xetr","yetr","zetr","wftr","xftr","yftr","zftr","wdur","xdur","ydur","zdur","weur","xeur","yeur","zeur","wfur","xfur","yfur","zfur","wdvr","xdvr","ydvr","zdvr","wevr","xevr","yevr","zevr","wfvr","xfvr","yfvr","zfvr","wdts","xdts","ydts","zdts","wets","xets","yets","zets","wfts","xfts","yfts","zfts","wdus","xdus","ydus","zdus","weus","xeus","yeus","zeus","wfus","xfus","yfus","zfus","wdvs","xdvs","ydvs","zdvs","wevs","xevs","yevs","zevs","wfvs","xfvs","yfvs","zfvs"]	["wdtp","xdtp","ydtp","zdtp","wetp","xetp","yetp","zetp","wftp","xftp","yftp","zftp","wdup","xdup","ydup","zdup","weup","xeup","yeup","zeup","wfup","xfup","yfup","zfup","wdvp","xdvp","ydvp","zdvp","wevp","xevp","yevp","zevp","wfvp","xfvp","yfvp","zfvp","wdtq","xdtq","ydtq","zdtq","wetq","xetq","yetq","zetq","wftq","xftq","yftq","zftq","wduq","xduq","yduq","zduq","weuq","xeuq","yeuq","zeuq","wfuq","xfuq","yfuq","zfuq","wdvq","xdvq","ydvq","zdvq","wevq","xevq","yevq","zevq","wfvq","xfvq","yfvq","zfvq","wdtr","xdtr","ydtr","zdtr","wetr","xetr","yetr","zetr","wftr","xftr","yftr","zftr","wdur","xdur","ydur","zdur","weur","xeur","yeur","zeur","wfur","xfur","yfur","zfur","wdvr","xdvr","ydvr","zdvr","wevr","xevr","yevr","zevr","wfvr","xfvr","yfvr","zfvr","wdts","xdts","ydts","zdts","wets","xets","yets","zets","wfts","xfts","yfts","zfts","wdus","xdus","ydus","zdus","weus","xeus","yeus","zeus","wfus","xfus","yfus","zfus","wdvs","xdvs","ydvs","zdvs","wevs","xevs","yevs","zevs","wfvs","xfvs","yfvs","zfvs"]
"2859"	["atjw","btjw","ctjw","aujw","bujw","cujw","avjw","bvjw","cvjw","atkw","btkw","ctkw","aukw","bukw","cukw","avkw","bvkw","cvkw","atlw","btlw","ctlw","aulw","bulw","culw","avlw","bvlw","cvlw","atjx","btjx","ctjx","aujx","bujx","cujx","avjx","bvjx","cvjx","atkx","btkx","ctkx","aukx","bukx","cukx","avkx","bvkx","cvkx","atlx","btlx","ctlx","aulx","bulx","culx","avlx","bvlx","cvlx","atjy","btjy","ctjy","aujy","bujy","cujy","avjy","bvjy","cvjy","atky","btky","ctky","auky","buky","cuky","avky","bvky","cvky","atly","btly","ctly","auly","buly","culy","avly","bvly","cvly","atjz","btjz","ctjz","aujz","bujz","cujz","avjz","bvjz","cvjz","atkz","btkz","ctkz","aukz","bukz","cukz","avkz","bvkz","cvkz","atlz","btlz","ctlz","aulz","bulz","culz","avlz","bvlz","cvlz"]	["atjw","btjw","ctjw","aujw","bujw","cujw","avjw","bvjw","cvjw","atkw","btkw","ctkw","aukw","bukw","cukw","avkw","bvkw","cvkw","atlw","btlw","ctlw","aulw","bulw","culw","avlw","bvlw","cvlw","atjx","btjx","ctjx","aujx","bujx","cujx","avjx","bvjx","cvjx","atkx","btkx","ctkx","aukx","bukx","cukx","avkx","bvkx","cvkx","atlx","btlx","ctlx","aulx","bulx","culx","avlx","bvlx","cvlx","atjy","btjy","ctjy","aujy","bujy","cujy","avjy","bvjy","cvjy","atky","btky","ctky","auky","buky","cuky","avky","bvky","cvky","atly","btly","ctly","auly","buly","culy","avly","bvly","cvly","atjz","btjz","ctjz","aujz","bujz","cujz","avjz","bvjz","cvjz","atkz","btkz","ctkz","aukz","bukz","cukz","avkz","bvkz","cvkz","atlz","btlz","ctlz","aulz","bulz","culz","avlz","bvlz","cvlz"]
"8888"	["tttt","uttt","vttt","tutt","uutt","vutt","tvtt","uvtt","vvtt","ttut","utut","vtut","tuut","uuut","vuut","tvut","uvut","vvut","ttvt","utvt","vtvt","tuvt","uuvt","vuvt","tvvt","uvvt","vvvt","tttu","uttu","vttu","tutu","uutu","vutu","tvtu","uvtu","vvtu","ttuu","utuu","vtuu","tuuu","uuuu","vuuu","tvuu","uvuu","vvuu","ttvu","utvu","vtvu","tuvu","uuvu","vuvu","tvvu","uvvu","vvvu","tttv","uttv","vttv","tutv","uutv","vutv","tvtv","uvtv","vvtv","ttuv","utuv","vtuv","tuuv","uuuv","vuuv","tvuv","uvuv","vvuv","ttvv","utvv","vtvv","tuvv","uuvv","vuvv","tvvv","uvvv","vvvv"]	["tttt","uttt","vttt","tutt","uutt","vutt","tvtt","uvtt","vvtt","ttut","utut","vtut","tuut","uuut","vuut","tvut","uvut","vvut","ttvt","utvt","vtvt","tuvt","uuvt","vuvt","tvvt","uvvt","vvvt","tttu","uttu","vttu","tutu","uutu","vutu","tvtu","uvtu","vvtu","ttuu","utuu","vtuu","tuuu","uuuu","vuuu","tvuu","uvuu","vvuu","ttvu","utvu","vtvu","tuvu","uuvu","vuvu","tvvu","uvvu","vvvu","tttv","uttv","vttv","tutv","uutv","vutv","tvtv","uvtv","vvtv","ttuv","utuv","vtuv","tuuv","uuuv","vuuv","tvuv","uvuv","vvuv","ttvv","utvv","vtvv","tuvv","uuvv","vuvv","tvvv","uvvv","vvvv"]
*/